name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - run: |
          mkdir -p path/to/artifact
          echo hello > path/to/artifact/world.txt

      - name: Basic usage
        uses: ./
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          name: 'azblob-upload-artifact'
          path: 'README.md'

      - name: Upload with path
        uses: ./
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          name: 'azblob-upload-artifact'
          path: 'path/to/artifact'
